### ISSUE TITLE
Avoid spaces and apostrophes in file names

### ISSUE THREAD

**Issue by Beliavsky** [NirupamKhanal/NumericalAnalysis#1]
I suggest renaming

[Euler's Method.f90](https://github.com/NirupamKhanal/NumericalAnalysis/blob/main/Euler's%20Method.f90)

to EulersMethod.f90

When file names have spaces or apostrophes, the user may need to put them in quotes to compile them from the command line, which is a hassle.

**Comment by NirupamKhanal** [comment]
> I suggest renaming
> 
> [Euler's Method.f90](https://github.com/NirupamKhanal/NumericalAnalysis/blob/main/Euler's%20Method.f90)
> 
> to EulersMethod.f90
> 
> When file names have spaces or apostrophes, the user may need to put them in quotes to compile them from the command line, which is a hassle.

Thanks for the advice -- I will change it!
